name: CI
on: [push, pull_request]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    name: make (stm32mp2)
    runs-on: ubuntu-latest
    container: jforissier/optee_os_ci
    steps:
      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: /github/home/.cache/ccache
          key: builds-cache-${{ github.sha }}
          restore-keys: |
            builds-cache-
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python
        shell: bash
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install pyelftools pillow cryptography pycryptodomex

      - name: Build
        shell: bash
        run: |
          set -e -v
          export LC_ALL=C
          export PATH=/usr/local/bin:$PATH  # clang
          export CROSS_COMPILE32="ccache arm-linux-gnueabihf-"
          export CROSS_COMPILE64="ccache aarch64-linux-gnu-"
          export CFG_DEBUG_INFO=n
          export CFG_WERROR=y

          ccache -s -v

          make -j$(nproc) PLATFORM=stm32mp2 PLATFORM_FLAVOR=257F_EV1 ARCH=arm ARM64_core=y CFG_EMBED_DTB_SOURCE_FILE=stm32mp257f-ev1.dts CFG_TEE_CORE_LOG_LEVEL=2

